fix: use NPM_CONFIG_USERCONFIG in get-registry to match auth
semantic-release/npm pull request #362
Opened 2021-04-29 16:38 UTC by jameshartig

Previously NPM_CONFIG_USERCONFIG was only used for getting the auth token and not used for actually getting the registry from .npmrc.

Fixes #349

2021-04-29 17:16 UTC, gr2m reviewed
Thanks for sending the pull request!

Can you please add a test to make sure we don't break this behavior in future!

2021-05-02 16:15 UTC, rodoabad approved these changes

2021-05-02 21:44 UTC, gr2m approved these changes
I confirmed locally that the test fails without the fix. Thanks for the PR @jameshartig 👍🏼

2021-05-02 21:44 UTC, gr2m requested changes
oh sorry, one more thing, I think we should document the env variable in https://github.com/semantic-release/npm#environment-variables?

2021-05-04 19:49 UTC, jameshartig commented
@gr2m good call! I updated the README

2021-05-04 20:45 UTC, gr2m approved these changes

2021-05-04 20:46 UTC, merged